version: "3"

services:
  www:
    build: .
    ports:
      - 80:80
    environment:
    - ENTRYPOINT_HOSTNAME=localhost
    - FRONTEND_ENDPOINT=http://localhost
    - LISTEN_PORT=80
    - DISABLE_SSL_HASH=#